project_id = "nqzzjpbotaawiatwyedb"

[functions.rfid-attendance]
verify_jwt = false

[functions.compute-payroll]
verify_jwt = false

[functions.create-employee]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.send-payslip-emails]
verify_jwt = false
